export const Strings = {
  appTitle: 'BLE Scanner',
  startScan: 'Start Scan',
  stopScan: 'Stop Scan',
  scanning: 'Scanning...',
  noDevicesFound: 'No Devices Found',
  noDevicesSubtext: 'Make sure Bluetooth is enabled and devices are nearby',
  searchPlaceholder: 'Search devices...',
  sortBy: 'Sort by',
  sortRssi: 'Signal Strength',
  sortName: 'Name',
  sortLastConnected: 'Last Connected',
  connected: 'Connected',
  disconnected: 'Disconnected',
  connecting: 'Connecting...',
  lastConnected: 'Last connected',
  never: 'Never',
  rssi: 'RSSI',
  deviceId: 'ID',
  readData: 'Read Data',
  writeData: 'Write Data',
  enterDataToWrite: 'Enter data to write (hex or text):',
  dataReceived: 'Data Received',
  readError: 'Failed to read data',
  writeError: 'Failed to write data',
  connectError: 'Failed to connect',
  disconnectError: 'Failed to disconnect',
  bluetoothRequired: 'Bluetooth Required',
  bluetoothRequiredMsg: 'Please enable Bluetooth to scan for devices',
  permissionRequired: 'Permission Required',
  permissionRequiredMsg: 'Location permission is required for BLE scanning',

  settingsTitle: 'Device Settings',
  settingsAutoConnect: 'Allow Auto-Connect',
  settingsAutoConnectDesc: 'Automatically connect to the preferred device when in range',
  settingsPreferredName: 'Preferred Device Name',
  settingsPreferredNamePlaceholder: 'e.g. My BLE Sensor',
  settingsConnectionTimeout: 'Connection Timeout',
  settingsConnectionTimeoutDesc: 'Time to wait before giving up on a connection',
  settingsNotificationPref: 'Notification Preference',
  settingsNotificationAll: 'All activity',
  settingsNotificationImportant: 'Important only',
  settingsNotificationNone: 'None',
  settingsSaved: 'Settings saved',
  settingsSave: 'Save',
};
